name = "hono"
main = "src/index.ts"
compatibility_date = "2023-01-01"
account_id = "$account_id"
compatibility_flags = ["nodejs_compat"]

#for dev 
# [dev]
# ip = "127.0.0.1"
# port = 8081
# local_protocol = "http"
[placement]
mode = "smart"

$ENV_SET
vars = { ENVIRONMENT = "$ENVIRONMENT" ,BASE_URL = "$BASE_URL"}
d1_databases =[{ binding = "DB" ,database_name = "$database_name" , database_id = "$database_id" , migrations_dir = "migrationsD1" }]




# production ----as no env
[vars]
ENVIRONMENT = "$ENVIRONMENT" 
BASE_URL = "$BASE_URL"



[[d1_databases]]
binding = "DB"
database_name = "$database_name"
database_id = "$database_id"
migrations_dir = "migrationsD1"




# ......