name = "hono"
main = "src/index.ts"
compatibility_date = "2023-01-01"
account_id = "$account_id"


compatibility_flags = ["nodejs_compat"]


[env.staging]
vars = { ENVIRONMENT = "staging" ,BASE_URL = "staging.example.com"}
d1_databases =[{ binding = "DB" ,database_name = "$db_staging" , database_id = "$database_id_staging" , migrations_dir = "migrationsD1" }]


[env.production]
vars = { ENVIRONMENT = "production" ,BASE_URL = "example.com"}
d1_databases =[{ binding = "DB" ,database_name = "$db_production" , database_id = "$database_id_production", migrations_dir = "migrationsD1" }]

