on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Genarate wrangler.toml
        run: |
          envsubst "`printf '${%s} ' $(sh -c "env|cut -d'=' -f1")`" < ./example.wrangler.toml > ./wrangler.toml
          echo "$(cat ./wrangler.toml)"
        env:
          ENVIRONMENT: dev
          BASE_URL: dev.example.com
          account_id: ${{ secrets.CF_ACCOUNT_ID }}
          database_name: cloudflare_fullstack_db
          database_id: ${{ secrets.database_id_dev }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: '${{ secrets.CF_ACCOUNT_ID }}'
          command: deploy
          environment: dev
