on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Genarate .toml
        run: |
          cp prod.wrangler.toml wrangler.toml 

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: "${{ secrets.CF_ACCOUNT_ID }}"
          command: deploy
          environment: staging
